### ISSUE TITLE
Package not working for Android/iOS/MacOS

### ISSUE THREAD

**Issue by abusaadp** [MobiliteDev/sqlcipher_library_windows#1]
Hi,
 This package works wonderfully for windows but for Android/iOS/MacOS the sqlite file is not encrypted. How to make it work for Android/iOS/MacOS?

**Comment by MobiliteDev** [comment]
This library is only to add the windows SQLCipher compatibility.

Tu use it, you need to user the [sqlcipher_flutter_libs](https://github.com/simolus3/sqlite3.dart/tree/main/sqlcipher_flutter_libs) library, which explains how to have Android/iOS and MacOS compatibility.
